import type { Metadata } from "next";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Script from 'next/script';
import Head from "next/head";

import '../styles/main.css';
import 'aos/dist/aos.css';
import 'bootstrap-icons/font/bootstrap-icons.css'; 
import 'bootstrap/dist/css/bootstrap.min.css';
import 'glightbox/dist/css/glightbox.min.css'; 

export const metadata: Metadata = {
  title: "Portfolio | Drashti Rathod",
  description: "Generated by Drashti Rathod",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <Head>
  <meta charSet="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <title>Portfolio | Drashti Rathod</title>
  <meta content="" name="description"/>
  <meta content="" name="keywords"/>

  <link rel="stylesheet" href="/assets/css/main.css" />
  {/* <!-- Favicons --> */}
  <link href="/assets/img/favicon.png" rel="icon"/>
  <link href="/assets/img/apple-touch-icon.png" rel="apple-touch-icon"/>

  {/* <!-- Fonts --> */}
  <link href="https://fonts.googleapis.com" rel="preconnect"/>
  <link href="https://fonts.gstatic.com" rel="preconnect" crossOrigin="anonymous"/>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>


</Head>



<body className="index-page">
  <Header />
        <main className="main">
          
          {children}
        </main>

  
  <Footer />

      <Script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"/>
      <Script src="assets/vendor/php-email-form/validate.js"/>
      <Script src="assets/vendor/aos/aos.js"/>
      <Script src="assets/vendor/typed.js/typed.umd.js"/>
      <Script src="assets/vendor/purecounter/purecounter_vanilla.js"/>
      <Script src="assets/vendor/waypoints/noframework.waypoints.js"/>
      <Script src="assets/vendor/glightbox/js/glightbox.min.js"/>
      <Script src="assets/vendor/imagesloaded/imagesloaded.pkgd.min.js"/>
      <Script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"/>
      <Script src="assets/vendor/swiper/swiper-bundle.min.js"/>

      {/* Your main JS file */}
      <Script src="assets/js/main.js"/>   

<Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossOrigin="anonymous"/>
      </body>
    </html>
  );
}
